name: attendance_nmsct
description: Flutter Web for Administrator.
publish_to: 'none' 


version: 2.0.0


environment:
  sdk: '>=3.1.3 <4.0.0'


dependencies:
  # ffi: ^2.0.1
  flutter:
    sdk: flutter


# ESSENTIAL
  intl: ^0.18.1

# STATE MANAGEMENT
  provider:

# FIREBASE
  firebase_core: ^2.31.0
  firebase_storage: ^11.7.5
  cloud_firestore: ^4.17.3
  firebase_database: ^10.5.5

# NETWORK
  http: ^0.13.6
  web_socket_channel: ^2.1.0
  connectivity_plus: ^5.0.2
  email_validator: ^2.1.17

# STORAGE
  shared_preferences: ^2.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sqflite: ^2.0.2

# MEDIA AND DOCUMENTS
  camera: ^0.9.4+19
  image: ^4.0.0
  flutter_camera: ^0.1.1
  image_picker: ^0.8.4+3
  open_file: ^3.3.2
  path: ^1.8.0
  path_provider: ^2.1.3
  pdf: ^3.11.0
  printing: ^5.5.0
  excel: ^2.0.7

# STYLING
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.6.0
  lottie: ^2.7.0
  flutter_platform_alert: ^0.5.1
  adaptive_action_sheet: ^2.0.2
  loader_skeleton: ^0.0.4
  shimmer: ^3.0.0
  flutter_staggered_grid_view: ^0.4.0
  awesome_notifications: ^0.8.2

# GOOGLE MAPS
  google_maps_flutter: ^2.6.1
  google_maps_webservice: ^0.0.20-nullsafety.5
  flutter_google_places_hoc081098: ^1.0.0-nullsafety.1
  google_api_headers: ^1.1.1
  location: ^5.0.3
  geolocator: ^9.0.2
  geocoding: ^2.0.5

# CALENDAR DATE TIME
  month_year_picker: ^0.3.0+1
  calendar_view: ^1.1.0

# WIDGET
  url_launcher: ^6.0.3
  timeline_tile: ^2.0.0
  flutter_keyboard_visibility: ^5.4.1
  get_it: ^7.2.0
  mailer: ^6.0.1



flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo.png"

dev_dependencies:
  # ffi: ^2.0.1
  ffigen: ^8.0.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.9
  permission_handler: ^10.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - assets/
  fonts:
    - family: MontserratBold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
     
    - family: MontserratRegular
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf

    - family: DejaVuSans
      fonts:
        - asset: assets/fonts/DejaVuSans.ttf